# -*- coding: utf-8 -*-
# Manifest reference:
# https://www.odoo.com/documentation/19.0/developer/reference/backend/module.html
{
    "name": "AI Dashboards Pro",
    "version": "19.0.3.0.0",
    "category": "Productivity/Dashboard",
    "summary": "Build Odoo dashboards by chatting with Claude, ChatGPT or any "
               "MCP client — then open them in Odoo like any other app. No API "
               "key, no generated SQL, every query runs as the person looking.",
    "description": """
AI Dashboards Pro
=================

Ask your own AI assistant for a dashboard. Get a real one in Odoo.

You already pay for Claude or ChatGPT. Connect it once, describe the dashboard
you want in plain English, and it lands in Odoo as an app you and your team
open like any other screen — P&L, Sales, Stock, whatever you asked for.

The AI never writes code
------------------------
It writes a **specification** — which model, which filter, which grouping,
which measures — and Odoo validates it and draws the charts. There is no
generated SQL anywhere in this module, which matters more than it sounds:
SQL generated by a language model runs outside the ORM and therefore outside
every access right and record rule your database has. A specification cannot
do that, because it is data rather than instructions.

Dashboards store the question, not the answer
---------------------------------------------
A saved dashboard holds *"revenue by month, this year"* — never the numbers.
The query runs when somebody opens it, **as that person**, through the ORM.
So a dashboard shared with a colleague shows their permitted slice, is never
stale, and respects multi-company boundaries without anyone configuring it.

What you get
------------
* **An app tile.** Dashboards live in their own Odoo app, not buried in a menu.
* **Preview before it is saved.** Nothing appears until you have looked at it.
* **Drill through.** Click a bar, get the records behind it in a normal list.
* **Edit by conversation.** Ask for a change; the assistant reads what exists
  and proposes a diff instead of rebuilding from scratch.
* **A light editor.** Drag to reorder, resize, rename, recolour — without
  going back to the chat for small things.
* **Every version kept.** One-click revert when a change was wrong.
* **Email it to yourself.** Every weekday, week or month — and each email is
  calculated with *your* permissions at the moment it is sent, so a shared
  dashboard mails each person their own figures rather than a copy of
  somebody else's.
* **Share with people or teams.** Sharing grants sight, never edit.
* **Compare against last year** — or the previous period — across the whole
  dashboard at once, switchable by whoever is reading it.
* **Pivot tables** over two dimensions, with both axes paged independently, so
  customers-by-month works on a real customer list rather than only a demo one.
* **It explains itself.** A plain-English account of exactly which data each
  dashboard reads and whose permissions it runs under.

Requires AI MCP, which provides the connection, the governance scope and the
audit trail. Dashboard tools appear on the connection you already have — one
URL, one sign-in, one log.
""",
    "author": "Fleet",
    "website": "https://fleet.ke",
    "support": "developers@fleet.ke,support@odin.ist,andrew@fleet.ke",
    "maintainer": "Fleet",
    "license": "OPL-1",  # Odoo Proprietary License (paid App Store module)
    "price": 149.00,
    "currency": "USD",
    # mcp_governance_suite brings the MCP transport, the OAuth 2.1 server, the
    # tool registry and the audit log. `bus` (used to tell an open browser a
    # dashboard is ready) arrives through its `mail` dependency.
    "depends": ["mcp_governance_suite"],
    "data": [
        "security/ai_dashboards_security.xml",
        "security/ir.model.access.csv",
        "data/mcp_capability_data.xml",
        "data/mail_template.xml",
        "data/ir_cron.xml",
        "views/ai_dashboard_views.xml",
        "views/ai_dashboard_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ai_dashboards/static/src/dashboard/*.scss",
            "ai_dashboards/static/src/dashboard/*.js",
            "ai_dashboards/static/src/dashboard/*.xml",
        ],
    },
    "pre_init_hook": "pre_init_check",
    "installable": True,
    "application": True,
}
