#!/usr/bin/env python3
"""Turn the extracted BizSure rate cards into Odoo data files.

The JSON under ``data/source`` is the input: products, quotation templates and
their lines, exactly as read from the configured database. Re-running this
script regenerates every XML file in ``data`` deterministically, so a rate
change is a change to the JSON plus one run, never hand-edited XML.

    python3 tools/generate_data.py
"""

import html as htmllib
import json
import os
import re
from xml.sax.saxutils import escape, quoteattr

HERE = os.path.dirname(os.path.abspath(__file__))
MODULE = os.path.dirname(HERE)
SOURCE = os.path.join(MODULE, "data", "source")
OUT = os.path.join(MODULE, "data")

HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/generate_data.py. Do not edit by hand. -->\n<odoo>\n'
FOOTER = "</odoo>\n"

#: first "KES 1,234,567" in a section title is the cover limit
KES = re.compile(r"KES\s*([\d,]+)")


def slug(value):
    out = re.sub(r"[^a-z0-9]+", "_", (value or "").lower()).strip("_")
    return re.sub(r"_+", "_", out)


def load(name):
    with open(os.path.join(SOURCE, name), encoding="utf-8") as fh:
        return json.load(fh)


def benefit_of(section_name):
    """Derive the client-facing benefit from a section title.

    Returns ``(label, key, cover_limit, is_optional)``. The limit is the first
    KES figure in the title: on Birdview the title also quotes the maternity
    sub-limit, which must not be mistaken for the plan limit.
    """
    name = section_name or ""
    low = name.lower()
    optional = low.startswith("optional")
    limit = 0.0
    found = KES.search(name)
    if found:
        limit = float(found.group(1).replace(",", ""))

    # Match whichever benefit is named FIRST. "Optional - dental cover (per
    # person, with outpatient cover)" is a dental section that merely mentions
    # outpatient; a fixed precedence would file it under Outpatient.
    needles = (
        ("inpatient", "Inpatient"),
        ("outpatient", "Outpatient"),
        ("maternity", "Maternity"),
        ("dental", "Dental"),
        ("optical", "Optical"),
        ("rider", "Riders"),
        ("statutory", "Statutory charges"),
        ("payment", "Payment options"),
    )
    hits = [(low.index(n), label) for n, label in needles if n in low]
    if hits:
        label = min(hits)[1]
        return label, slug(label), limit, optional
    return name.strip(), slug(name), limit, optional


def as_xml_html(raw):
    """Re-serialise editor HTML as well-formed XML for an html field."""
    if not raw:
        return ""
    try:
        from lxml import etree, html as lhtml
    except ImportError:  # fall back to escaping; the field then needs a fix-up
        return escape(raw)
    fragment = lhtml.fragment_fromstring(raw, create_parent="div")
    out = etree.tostring(fragment, encoding="unicode", method="xml")
    return out[len("<div>"):-len("</div>")] if out.startswith("<div>") else out


def field(name, value=None, ref=None, eval_=None, type_=None):
    if ref is not None:
        return '        <field name="%s" ref="%s"/>\n' % (name, ref)
    if eval_ is not None:
        return '        <field name="%s" eval=%s/>\n' % (name, quoteattr(eval_))
    if type_ == "html":
        return '        <field name="%s" type="html">%s</field>\n' % (name, value)
    return '        <field name="%s">%s</field>\n' % (name, escape(str(value)))


# ---------------------------------------------------------------- categories

def write_categories(categories):
    body = HEADER
    for cat in categories:
        xmlid = "categ_%s" % slug(cat["complete_name"].replace("Insurance Premiums", "ins"))
        body += '    <record id="%s" model="product.category">\n' % xmlid
        body += field("name", cat["name"])
        if cat["parent_id"]:
            parent = next(c for c in categories if c["id"] == cat["parent_id"][0])
            body += field("parent_id", ref="categ_%s" % slug(
                parent["complete_name"].replace("Insurance Premiums", "ins")))
        body += "    </record>\n\n"
    body += FOOTER
    open(os.path.join(OUT, "product_category.xml"), "w", encoding="utf-8").write(body)
    return {c["id"]: "categ_%s" % slug(c["complete_name"].replace("Insurance Premiums", "ins"))
            for c in categories}


# --------------------------------------------------------------------- taxes

def write_taxes():
    body = HEADER
    body += '    <record id="tax_group_insurance_levies" model="account.tax.group">\n'
    body += field("name", "Insurance Levies")
    body += field("sequence", 50)
    body += "    </record>\n\n"
    for xmlid, name, amount, note in (
        ("tax_training_levy", "Training Levy 0.2%", 0.2,
         "Insurance Training Levy &#8211; 0.2% of basic premium"),
        ("tax_phcf", "PHCF 0.25%", 0.25,
         "Policyholders' Compensation Fund levy &#8211; 0.25% of basic premium"),
    ):
        body += '    <record id="%s" model="account.tax">\n' % xmlid
        body += field("name", name)
        body += field("amount", amount)
        body += field("amount_type", "percent")
        body += field("type_tax_use", "sale")
        body += field("price_include_override", "tax_excluded")
        body += field("tax_group_id", ref="tax_group_insurance_levies")
        body += field("country_id", ref="base.ke")
        body += '        <field name="description" type="html"><div>%s</div></field>\n' % note
        body += "    </record>\n\n"
    body += FOOTER
    open(os.path.join(OUT, "account_tax.xml"), "w", encoding="utf-8").write(body)


# ------------------------------------------------------------------ products

def write_products(products, cat_xmlids):
    """Written as product.product: it delegates to product.template via
    _inherits, so one record creates both, and template lines can point at it."""
    body = HEADER
    seen = {}
    for prod in products:
        xmlid = "prod_%s" % slug(prod["default_code"])
        if xmlid in seen:
            raise SystemExit("external id collision: %s and %s both give %s"
                             % (seen[xmlid], prod["default_code"], xmlid))
        seen[xmlid] = prod["default_code"]
        body += '    <record id="%s" model="product.product">\n' % xmlid
        body += field("name", prod["name"])
        body += field("default_code", prod["default_code"])
        body += field("type", "service")
        body += field("list_price", prod["list_price"])
        body += field("sale_ok", eval_="True" if prod["sale_ok"] else "False")
        body += field("purchase_ok", eval_="False")
        body += field("invoice_policy", "order")
        # IPF-* carry the cost of paying monthly, not cover. Flagging them keeps
        # them out of the premium an instalment schedule is worked out from, so
        # interest is never charged on interest. FEE-STAMP is a real statutory
        # charge and stays part of the premium.
        if prod["default_code"].startswith("IPF-"):
            body += field("odin_instalment_interest", eval_="True")
        body += field("uom_id", ref="uom.product_uom_unit")
        if prod["categ_id"]:
            body += field("categ_id", ref=cat_xmlids[prod["categ_id"][0]])
        if prod.get("description_sale"):
            body += field("description_sale", prod["description_sale"])
        if prod["taxes_id"]:
            body += field("taxes_id", eval_=
                          "[(6, 0, [ref('tax_training_levy'), ref('tax_phcf')])]")
        else:
            body += field("taxes_id", eval_="[(5, 0, 0)]")
        body += "    </record>\n\n"
    body += FOOTER
    open(os.path.join(OUT, "product_template.xml"), "w", encoding="utf-8").write(body)
    # keyed by product code: template lines reference product.product ids,
    # which are not the same numbers as product.template ids
    return {p["default_code"]: "prod_%s" % slug(p["default_code"]) for p in products}


# ----------------------------------------------------------------- templates

def write_templates(templates, lines, prod_xmlids):
    by_template = {}
    for line in lines:
        by_template.setdefault(line["sale_order_template_id"][0], []).append(line)

    body = HEADER
    for tmpl in sorted(templates, key=lambda t: t["sequence"]):
        xmlid = "sot_%s" % slug(tmpl["name"])
        body += '    <record id="%s" model="sale.order.template">\n' % xmlid
        body += field("name", tmpl["name"])
        body += field("sequence", tmpl["sequence"])
        body += field("number_of_days", tmpl["number_of_days"])
        body += field("require_signature", eval_="True" if tmpl["require_signature"] else "False")
        body += field("require_payment", eval_="True" if tmpl["require_payment"] else "False")
        if tmpl.get("note"):
            body += field("note", as_xml_html(tmpl["note"]), type_="html")
        body += "    </record>\n\n"

        for index, line in enumerate(sorted(by_template.get(tmpl["id"], []),
                                            key=lambda l: (l["sequence"], l["id"]))):
            line_id = "%s_l%03d" % (xmlid, index)
            body += '    <record id="%s" model="sale.order.template.line">\n' % line_id
            body += field("sale_order_template_id", ref=xmlid)
            body += field("sequence", line["sequence"])
            if line["display_type"]:
                body += field("display_type", line["display_type"])
            if line["name"]:
                body += field("name", line["name"])
            if line["product_id"]:
                code = line["product_code"]
                body += field("product_id", ref=prod_xmlids[code])
                body += field("product_uom_id", ref="uom.product_uom_unit")
            body += field("product_uom_qty", line["product_uom_qty"])
            if line["display_type"] == "line_section":
                label, key, limit, optional = benefit_of(line["name"])
                body += field("benefit_label", label)
                body += field("benefit_key", key)
                if limit:
                    body += field("cover_limit", limit)
                if optional:
                    body += field("is_optional", eval_="True")
            body += "    </record>\n\n"
    body += FOOTER
    open(os.path.join(OUT, "sale_order_template.xml"), "w", encoding="utf-8").write(body)


def main():
    categories = load("product_category.json")
    products = load("product_template.json")
    templates = load("sale_order_template.json")
    lines = load("sale_order_template_line.json")

    cat_xmlids = write_categories(categories)
    write_taxes()
    prod_xmlids = write_products(products, cat_xmlids)
    write_templates(templates, lines, prod_xmlids)
    print("categories %d | products %d | templates %d | template lines %d"
          % (len(categories), len(products), len(templates), len(lines)))


if __name__ == "__main__":
    main()
