from . import (
    crm_lead,
    discuss_channel,
    discuss_channel_member,
    discuss_channel_routing,
    ir_actions_server,
    mail_message,
    mail_thread,
    res_partner,
    whatsapp_account,
    whatsapp_message,
    whatsapp_operator,
    whatsapp_routing_config,
    whatsapp_template,
    whatsapp_webhook_event,
)
