from . import whatsapp_account
from . import whatsapp_operator
from . import whatsapp_template
from . import whatsapp_message
from . import whatsapp_webhook_event
from . import discuss_channel
from . import mail_message
from . import res_partner
from . import crm_lead
