import secrets

from odoo import api, fields, models

WEBHOOK_ROUTE = "/whatsapp_connector/webhook"


class WhatsappAccount(models.Model):
    """A WhatsApp Business Account and its business phone number (SPEC.md §4)."""

    _name = "whatsapp_connector.account"
    _description = "WhatsApp Business Account"
    _inherit = ["mail.thread"]
    _order = "sequence, id"

    name = fields.Char(required=True, tracking=True)
    sequence = fields.Integer(default=10)
    active = fields.Boolean(default=True, tracking=True)
    company_id = fields.Many2one(
        "res.company", required=True, default=lambda self: self.env.company, tracking=True,
    )

    # Connection (labels as in Odoo Enterprise, R2)
    waba_id = fields.Char(
        "Account ID", required=True, tracking=True,
        help="WhatsApp Business Account ID, from the Meta App Dashboard > WhatsApp > API Setup.",
    )
    phone_number_id = fields.Char(
        "Phone Number ID", required=True, tracking=True,
        help="From the Meta App Dashboard > WhatsApp > API Setup.",
    )
    app_id = fields.Char("App ID", tracking=True)
    app_secret = fields.Char(
        "App Secret", copy=False, groups="whatsapp_connector.group_whatsapp_admin",
        help="Meta App Dashboard > App settings > Basic. Used to check that webhooks come from Meta.",
    )
    access_token = fields.Char(
        "Access Token", copy=False, groups="whatsapp_connector.group_whatsapp_admin",
        help="A permanent System User token with business_management, whatsapp_business_messaging, "
        "whatsapp_business_management and whatsapp_business_manage_events.",
    )
    # No "current" Graph API version is hard-coded (N1): the administrator sets it.
    api_version = fields.Char(
        "API Version", required=True, tracking=True,
        help="Graph API version used for every call, for example v25.0. "
        "Meta lists the supported versions in its changelog.",
    )
    phone_number = fields.Char(
        "Phone Number", readonly=True, copy=False,
        help="The business number, as Meta reports it on Test Connection.",
    )
    verified_name = fields.Char("Business Display Name", readonly=True, copy=False)
    quality_rating = fields.Char(readonly=True, copy=False)
    connection_state = fields.Selection(
        [
            ("not_tested", "Not tested"),
            ("connected", "Connected"),
            ("connection_error", "Connection Error"),
            ("webhook_error", "Webhook Error"),
            ("token_error", "Token Error"),
        ],
        string="Connection Status", default="not_tested", required=True, readonly=True, copy=False,
    )
    connection_message = fields.Text(readonly=True, copy=False)
    connection_tested_at = fields.Datetime("Last Tested", readonly=True, copy=False)

    # Receiving Messages (generated by Odoo, R2)
    callback_url = fields.Char("Callback URL", compute="_compute_callback_url")
    webhook_verify_token = fields.Char(
        "Webhook Verify Token", readonly=True, copy=False,
        groups="whatsapp_connector.group_whatsapp_admin",
    )

    # Control (R3): the account's Notify users; C2: the only per-account user list.
    operator_ids = fields.One2many(
        "whatsapp_connector.operator", "account_id", string="Notify users",
        context={"active_test": False},
    )
    notify_user_ids = fields.Many2many(
        "res.users", string="Notify users (active)", compute="_compute_notify_user_ids",
    )

    # Conversation Routing (C1: stored here only)
    routing_mode = fields.Selection(
        [("none", "No Lead Routing"), ("lead", "Lead Routing")],
        string="Conversation Routing", default="none", required=True, tracking=True,
        help="No Lead Routing: the standard Odoo WhatsApp conversation model. Incoming customer "
        "conversations are handled through Discuss by the account's Notify users.\n"
        "Lead Routing: automatically assign incoming WhatsApp conversations to individual Odoo "
        "users and link them to CRM leads.",
    )
    bsuid_sending_enabled = fields.Boolean(
        "Send to business-scoped user IDs",
        help="Send to a customer's business-scoped user ID when no phone number is known. "
        "Meta documents this as available from July 2026; enable it once Meta accepts it for "
        "this number.",
    )

    channel_ids = fields.One2many("discuss.channel", "wa_account_id", string="Conversations")
    channel_count = fields.Integer("Conversation Count", compute="_compute_counts")
    template_ids = fields.One2many("whatsapp_connector.template", "account_id", string="Templates")
    template_count = fields.Integer("Template Count", compute="_compute_counts")

    _phone_number_id_unique = models.UniqueIndex(
        "(phone_number_id) WHERE active IS TRUE",
        "Another active account already uses this Phone Number ID.",
    )

    @api.depends_context("uid")
    def _compute_callback_url(self):
        for account in self:
            account.callback_url = f"{account.get_base_url()}{WEBHOOK_ROUTE}"

    @api.depends("operator_ids.user_id", "operator_ids.active", "operator_ids.user_id.active")
    def _compute_notify_user_ids(self):
        for account in self:
            account.notify_user_ids = account.operator_ids.filtered(
                lambda op: op.active and op.user_id.active
            ).user_id

    def _compute_counts(self):
        for account in self:
            account.channel_count = len(account.channel_ids)
            account.template_count = len(account.template_ids)

    def _ensure_webhook_verify_token(self):
        for account in self.sudo():
            if not account.webhook_verify_token:
                account.webhook_verify_token = secrets.token_urlsafe(24)

    def action_open_conversations(self):
        self.ensure_one()
        action = self.env["ir.actions.act_window"]._for_xml_id(
            "whatsapp_connector.action_whatsapp_conversations"
        )
        action["domain"] = [("wa_account_id", "=", self.id)]
        return action

    def action_open_templates(self):
        self.ensure_one()
        action = self.env["ir.actions.act_window"]._for_xml_id(
            "whatsapp_connector.action_whatsapp_template"
        )
        action["domain"] = [("account_id", "=", self.id)]
        action["context"] = {"default_account_id": self.id}
        return action
