import logging
import secrets

from odoo import api, fields, models
from odoo.exceptions import UserError

from odoo.addons.whatsapp_connector.tools.meta_api import MetaApiError, WhatsAppApi

_logger = logging.getLogger(__name__)

WEBHOOK_ROUTE = "/whatsapp_connector/webhook"


class WhatsappAccount(models.Model):
    """A WhatsApp Business Account and its business phone number (SPEC.md §4)."""

    _name = "whatsapp_connector.account"
    _description = "WhatsApp Business Account"
    _inherit = ["mail.thread"]
    _order = "sequence, id"

    name = fields.Char(required=True, tracking=True)
    sequence = fields.Integer(default=10)
    active = fields.Boolean(default=True, tracking=True)
    company_id = fields.Many2one(
        "res.company", required=True, default=lambda self: self.env.company, tracking=True,
    )

    # Connection (labels as in Odoo Enterprise, R2)
    waba_id = fields.Char(
        "Account ID", required=True, tracking=True,
        help="WhatsApp Business Account ID, from the Meta App Dashboard > WhatsApp > API Setup.",
    )
    phone_number_id = fields.Char(
        "Phone Number ID", required=True, tracking=True,
        help="From the Meta App Dashboard > WhatsApp > API Setup.",
    )
    app_id = fields.Char("App ID", tracking=True)
    app_secret = fields.Char(
        "App Secret", copy=False, groups="whatsapp_connector.group_whatsapp_admin",
        help="Meta App Dashboard > App settings > Basic. Used to check that webhooks come from Meta.",
    )
    access_token = fields.Char(
        "Access Token", copy=False, groups="whatsapp_connector.group_whatsapp_admin",
        help="A permanent System User token with business_management, whatsapp_business_messaging, "
        "whatsapp_business_management and whatsapp_business_manage_events.",
    )
    # No "current" Graph API version is hard-coded (N1): the administrator sets it.
    api_version = fields.Char(
        "API Version", required=True, tracking=True,
        help="Graph API version used for every call, for example v25.0. "
        "Meta lists the supported versions in its changelog.",
    )
    phone_number = fields.Char(
        "Phone Number", readonly=True, copy=False,
        help="The business number, as Meta reports it on Test Connection.",
    )
    verified_name = fields.Char("Business Display Name", readonly=True, copy=False)
    quality_rating = fields.Char(readonly=True, copy=False)
    connection_state = fields.Selection(
        [
            ("not_tested", "Not tested"),
            ("connected", "Connected"),
            ("connection_error", "Connection Error"),
            ("webhook_error", "Webhook Error"),
            ("token_error", "Token Error"),
        ],
        string="Connection Status", default="not_tested", required=True, readonly=True, copy=False,
    )
    connection_message = fields.Text(readonly=True, copy=False)
    connection_tested_at = fields.Datetime("Last Tested", readonly=True, copy=False)

    # Receiving Messages (generated by Odoo, R2)
    callback_url = fields.Char("Callback URL", compute="_compute_callback_url")
    webhook_verify_token = fields.Char(
        "Webhook Verify Token", readonly=True, copy=False,
        groups="whatsapp_connector.group_whatsapp_admin",
    )

    # Control (R3): the account's Notify users; C2: the only per-account user list.
    operator_ids = fields.One2many(
        "whatsapp_connector.operator", "account_id", string="Notify users",
        context={"active_test": False},
    )
    notify_user_ids = fields.Many2many(
        "res.users", string="Notify users (active)", compute="_compute_notify_user_ids",
    )

    # Conversation Routing (C1: stored here only)
    routing_mode = fields.Selection(
        [("none", "No Lead Routing"), ("lead", "Lead Routing")],
        string="Conversation Routing", default="none", required=True, tracking=True,
        help="No Lead Routing: the standard Odoo WhatsApp conversation model. Incoming customer "
        "conversations are handled through Discuss by the account's Notify users.\n"
        "Lead Routing: automatically assign incoming WhatsApp conversations to individual Odoo "
        "users and link them to CRM leads.",
    )
    routing_config_id = fields.Many2one(
        "whatsapp_connector.routing.config", "Routing Configuration", readonly=True, copy=False,
        ondelete="set null",
    )
    routing_method = fields.Selection(related="routing_config_id.method", readonly=False)
    routing_fallback_user_id = fields.Many2one(
        related="routing_config_id.fallback_user_id", readonly=False, string="Fallback User",
    )
    routing_last_assigned_user_id = fields.Many2one(
        related="routing_config_id.last_assigned_user_id", string="Last Assigned",
    )
    bsuid_sending_enabled = fields.Boolean(
        "Send to business-scoped user IDs",
        help="Send to a customer's business-scoped user ID when no phone number is known. "
        "Meta documents this as available from July 2026; enable it once Meta accepts it for "
        "this number.",
    )

    channel_ids = fields.One2many("discuss.channel", "wa_account_id", string="Conversations")
    channel_count = fields.Integer("Conversation Count", compute="_compute_counts")
    template_ids = fields.One2many("whatsapp_connector.template", "account_id", string="Templates")
    template_count = fields.Integer("Template Count", compute="_compute_counts")

    _phone_number_id_unique = models.UniqueIndex(
        "(phone_number_id) WHERE active IS TRUE",
        "Another active account already uses this Phone Number ID.",
    )

    @api.model_create_multi
    def create(self, vals_list):
        accounts = super().create(vals_list)
        accounts._wa_routing_config()
        return accounts

    def write(self, vals):
        if {"routing_method", "routing_fallback_user_id"}.intersection(vals):
            # the routing settings are related fields, written only when the
            # configuration row exists (accounts created before Lead Routing)
            self._wa_routing_config()
        return super().write(vals)

    def _wa_routing_config(self):
        """The account's routing configuration (§53.1), created when missing."""
        for account in self.sudo().filtered(lambda a: not a.routing_config_id):
            account.routing_config_id = self.env["whatsapp_connector.routing.config"].sudo().create({
                "account_id": account.id,
            })
        return self.sudo().routing_config_id

    @api.depends_context("uid")
    def _compute_callback_url(self):
        for account in self:
            account.callback_url = f"{account.get_base_url()}{WEBHOOK_ROUTE}"

    @api.depends("operator_ids.user_id", "operator_ids.active", "operator_ids.user_id.active")
    def _compute_notify_user_ids(self):
        for account in self:
            account.notify_user_ids = account.operator_ids.filtered(
                lambda op: op.active and op.user_id.active,
            ).user_id

    def _compute_counts(self):
        for account in self:
            account.channel_count = len(account.channel_ids)
            account.template_count = len(account.template_ids)

    def _ensure_webhook_verify_token(self):
        for account in self.sudo():
            if not account.webhook_verify_token:
                account.webhook_verify_token = secrets.token_urlsafe(24)

    def action_open_conversations(self):
        self.ensure_one()
        action = self.env["ir.actions.act_window"]._for_xml_id(
            "whatsapp_connector.action_whatsapp_conversations",
        )
        action["domain"] = [("wa_account_id", "=", self.id)]
        return action

    def action_open_templates(self):
        self.ensure_one()
        action = self.env["ir.actions.act_window"]._for_xml_id(
            "whatsapp_connector.action_whatsapp_template",
        )
        action["domain"] = [("account_id", "=", self.id)]
        action["context"] = {"default_account_id": self.id}
        return action

    # ------------------------------------------------------------------
    # Test Connection (SPEC.md §34, R24)
    # ------------------------------------------------------------------

    def _api(self):
        self.ensure_one()
        return WhatsAppApi(self)

    def action_test_connection(self):
        """Check the number and the webhook subscription with Meta for real (§34)."""
        self.ensure_one()
        self._ensure_webhook_verify_token()
        state, message, vals = self._wa_check_connection()
        vals.update({
            "connection_state": state,
            "connection_message": message,
            "connection_tested_at": fields.Datetime.now(),
        })
        self.sudo().write(vals)
        return self._notify(
            message, "success" if state == "connected" else "danger", sticky=state != "connected",
        )

    def _wa_check_connection(self):
        tr = self.env._
        vals = {}
        try:
            api_client = self._api()
            number = api_client.get_phone_number()
        except MetaApiError as e:
            if e.is_token_error:
                return "token_error", tr("Meta refused the access token: %s", e), vals
            return "connection_error", tr("Meta refused the request: %s", e), vals
        vals.update({
            "phone_number": number.get("display_phone_number") or False,
            "verified_name": number.get("verified_name") or False,
            "quality_rating": number.get("quality_rating") or False,
        })
        number_status = (number.get("status") or "").upper()
        if number_status and number_status != "CONNECTED":
            return "connection_error", tr(
                "Meta reports the number as %s: it must be CONNECTED to send and receive messages.",
                number_status,
            ), vals
        try:
            subscribed = api_client.get_subscribed_apps()
        except MetaApiError as e:
            return "webhook_error", tr("Could not read the app subscriptions: %s", e), vals
        if self.app_id and self.app_id not in subscribed:
            return "webhook_error", tr(
                "The app %(app)s is not subscribed to this WhatsApp Business Account, so Meta "
                "sends it no webhooks. Click Subscribe App, then set the Callback URL and Verify "
                "Token in Meta's App Dashboard.", app=self.app_id,
            ), vals
        return "connected", tr(
            "Connected. Meta will deliver messages to %(url)s once the webhook is configured in "
            "the App Dashboard with this Verify Token. The Meta app must be Live: in Development "
            "mode only test numbers can be messaged and some webhooks are not sent.",
            url=self.callback_url,
        ), vals

    def action_subscribe_app(self):
        self.ensure_one()
        try:
            self._api().subscribe_app()
        except MetaApiError as e:
            raise UserError(self.env._("Meta refused the subscription: %s", e)) from None
        return self.action_test_connection()

    def action_regenerate_verify_token(self):
        for account in self.sudo():
            account.webhook_verify_token = secrets.token_urlsafe(24)

    # ------------------------------------------------------------------
    # Templates (R25)
    # ------------------------------------------------------------------

    def action_sync_templates(self):
        self.ensure_one()
        try:
            count = self._wa_sync_templates(raise_on_error=True)
        except MetaApiError as e:
            raise UserError(self.env._("Could not read the templates from Meta: %s", e)) from None
        return self._notify(self.env._("%s templates synced from Meta.", count), "success")

    def _wa_sync_templates(self, raise_on_error=False):
        self.ensure_one()
        try:
            meta_templates = self._api().get_templates()
        except MetaApiError:
            if raise_on_error:
                raise
            _logger.warning("WhatsApp: template sync failed for account %s", self.id, exc_info=True)
            return 0
        return self.env["whatsapp_connector.template"].sudo()._wa_sync_account(self, meta_templates)

    def _notify(self, message, kind, sticky=False):
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "message": message,
                "type": kind,
                "sticky": sticky,
                "next": {"type": "ir.actions.client", "tag": "soft_reload"},
            },
        }
