from . import product
from . import res_users
from . import hr_employee
from . import res_partner
from . import odin_bar_reason
from . import odin_bar_variance_reason
from . import odin_bar
from . import odin_bar_activity
from . import odin_bar_count
from . import stock
from . import odin_bar_desk
from . import odin_bar_desk_supply
from . import odin_bar_reports
from . import odin_bar_dashboard
